# -*- coding: utf-8 -*-
"""Module4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eFusqrfdaRSiGcoL2zsV32E5TFOdP1Ha

INSTALL LIBRARY
"""

!pip install transformers datasets scikit-learn sastrawi

"""IMPORT"""

import pandas as pd
import numpy as np
import re
import torch

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    pipeline
)

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

"""LOAD DATASET"""

df = pd.read_csv("/content/ulasan_playstore_livin.csv", sep=';', on_bad_lines='skip')

df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df = df[['content']].dropna()

print(df.head())

"""PREPROCESSING"""

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def preprocess(text):
    text = str(text).lower()
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['clean'] = df['content'].apply(preprocess)
df.head()

"""AUTO LABEL EMOSI (NLP + RULE HYBRID 🔥)"""

from transformers import pipeline

sentiment_model = pipeline(
    "sentiment-analysis",
    model="w11wo/indonesian-roberta-base-sentiment-classifier"
)

def auto_emotion_label(text):
    text_low = text.lower()

    result = sentiment_model(text[:512])[0]['label']

    # DEBUG (boleh aktifkan sementara)
    # print(result)

    if result == "positive":
        return "senang"

    elif result == "negative":
        if any(k in text_low for k in ["marah", "kesal", "parah"]):
            return "marah"
        elif any(k in text_low for k in ["sedih", "mengecewakan"]):
            return "sedih"
        elif any(k in text_low for k in ["error", "gagal", "lambat", "tidak bisa"]):
            return "kecewa"
        else:
            return "kecewa"

    return "netral"

df['emotion'] = df['clean'].apply(auto_emotion_label)

print(df['emotion'].value_counts())

"""DETEKSI SARKASEMSE"""

def detect_sarcasm(text):
    text = text.lower()

    patterns = [
        ("bagus", "error"),
        ("mantap", "lambat"),
        ("keren", "gagal"),
        ("hebat", "buruk")
    ]

    for pos, neg in patterns:
        if pos in text and neg in text:
            return 1

    return 0

df['sarcasm'] = df['clean'].apply(detect_sarcasm)
df.head()

"""ENCODING LABEL"""

label2id = {
    "senang": 0,
    "marah": 1,
    "sedih": 2,
    "kecewa": 3,
    "netral": 4
}

id2label = {v: k for k, v in label2id.items()}

df['label_id'] = df['emotion'].map(label2id)
df.head(20)

"""SPLIT DATA"""

train_texts, val_texts, train_labels, val_labels = train_test_split(
    df['clean'],
    df['label_id'],
    test_size=0.2,
    random_state=42,
    stratify=df['label_id']
)

"""TOKENIZATION"""

model_name = "indobenchmark/indobert-base-p1"

tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize(texts):
    return tokenizer(list(texts), padding=True, truncation=True, max_length=128)

train_encodings = tokenize(train_texts)
val_encodings = tokenize(val_texts)

"""DATASET CLASS"""

class Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels.reset_index(drop=True)

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = Dataset(train_encodings, train_labels)
val_dataset = Dataset(val_encodings, val_labels)

"""LOAD MODEL"""

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=5,
    id2label=id2label,
    label2id=label2id
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

"""TRAINING CONFIG"""

training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    num_train_epochs=5
    # evaluation_strategy="epoch" # Removed to fix TypeError
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset
)

trainer.train()

"""EVALUASI"""

predictions = trainer.predict(val_dataset)

y_pred = np.argmax(predictions.predictions, axis=1)
y_true = val_labels.values

print(classification_report(
    y_true,
    y_pred,
    target_names=list(label2id.keys()),
    labels=list(id2label.keys()) # Explicitly specify all possible labels
))

"""PREDICT FINAL"""

def predict(text):
    model.eval()

    clean_text = preprocess(text)

    inputs = tokenizer(clean_text, return_tensors="pt", truncation=True, padding=True)
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)

    probs = torch.softmax(outputs.logits, dim=1)

    pred_id = torch.argmax(probs, dim=1).item()

    emotion = id2label[pred_id]
    sarcasm = detect_sarcasm(text)

    return emotion, sarcasm

"""TEST"""

text = "Orang Karyawan nyaa pada ramah, sopan, baik.."

emotion, sarcasm = predict(text)

print("Teks:", text)
print("Emosi:", emotion)
print("Sarkasme:", "Ya" if sarcasm else "Tidak")

"""BULK TESTING"""

def predict_bulk(file_path, output_path="hasil_prediksi.csv"):
    df_test = pd.read_csv(file_path)

    if 'content' not in df_test.columns:
        raise ValueError("Kolom 'content' wajib ada")

    emotions = []
    sarcasms = []

    for text in df_test['content']:
        emotion, sarcasm = predict(text)

        emotions.append(emotion)
        sarcasms.append("Ya" if sarcasm else "Tidak")

    df_test['emotion'] = emotions
    df_test['sarcasm'] = sarcasms

    df_test.to_csv(output_path, index=False)

    print("✅ Hasil disimpan di:", output_path)

    return df_test

# Create a dummy test_bulk.csv file for demonstration
df.head(10)[['content']].to_csv('test_bulk.csv', index=False)

result = predict_bulk("test_bulk.csv")
result.head(25)